:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 10 %>
:queues:
  # NOTE(ezekg) The higher the weight, the more often it is checked.
  - [critical, 2]
  - [deletes, 1] # Deprecated
  - [webhooks, 1]
  - [default, 1]
  - [mailers, 1]
  - [billing, 1]
  - [metrics, 1]
  - [system, 1] # Deprecated
  - [logs, 1]
  - [cron, 1]
# :queues:
#   # NOTE(ezekg) The higher the weight, the more often it is checked.
#   - [critical, 10]
#   - [deletes, 6] # Deprecated
#   - [webhooks, 5]
#   - [default, 4]
#   - [mailers, 3]
#   - [billing, 2]
#   - [metrics, 1]
#   - [system, 1] # Deprecated
#   - [logs, 1]
#   - [cron, 1]
